### ISSUE TITLE
Api error when the ngMessageCenter doesn't exists

### ISSUE THREAD

**Issue by RoxRicardo** [federicot/ng-message-center#5]
When you make call like 
```javascript
ngMessageCenter.success({name: 'sidebar', title: 'Well done!', text: 'Client was successfully saved', next: true});
```
and the tag <ngmessagecenter-messages /> doesn't exists with name "sidebar", the api generate error 
```javascript
TypeError: Cannot read property 'current' of undefined
    at Object.service.clear (http://localhost:60636/StyleGuide/bower_components/ng-message-center/ng-message-center.js:60:31)
    at Object.service.add (http://localhost:60636/StyleGuide/bower_components/ng-message-center/ng-message-center.js:36:22)
```
I think that would be better if the api prints error message telling the problem.

If you agree I can implement this.

**Comment by federicot** [comment]
Yes, that would be nice.
